{"name":"test",
"releases":[{"name":"java","version":"create","url":"file://."}],
"stemcells":[{"alias":"default","os":"ubuntu-jammy","version":"latest"}],
"update":{"canaries":2,"max_in_flight":1,"canary_watch_time":"5000-60000","update_watch_time":"5000-60000"},
"instance_groups":[
{"name":"openjdk-test",
"azs":["z1"],
"instances":1,
"lifecycle":"errand",
"jobs":[{"name":"openjdk-11-test","release":"java","properties":{}}],
"vm_type":"default",
"stemcell":"default",
"networks":[{"name":"default"}]}]}
